apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/cmcgow061408/book-microservice:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/cmcgow061408/book-microservice:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: book-microservice
        chartPath: charts/book-microservice
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/cmcgow061408/book-microservice"
          image.tag: "{{.TAG}}"
        